const
  VERTEX_ATTRIBUTE_POSITION* = 1 shl 0
  VERTEX_ATTRIBUTE_QPOSITION* = 1 shl 1
  VERTEX_ATTRIBUTE_NORMAL* = 1 shl 2
  VERTEX_ATTRIBUTE_QNORMAL* = 1 shl 3
  VERTEX_ATTRIBUTE_COLOR* = 1 shl 4
  VERTEX_ATTRIBUTE_TANGENT* = 1 shl 5
  VERTEX_ATTRIBUTE_QTANGENT* = 1 shl 6
  VERTEX_ATTRIBUTE_BITANGENT* = 1 shl 7
  VERTEX_ATTRIBUTE_TEXCOORD0* = 1 shl 8
  VERTEX_ATTRIBUTE_QTEXCOORD0* = 1 shl 9
  VERTEX_ATTRIBUTE_TEXCOORD1* = 1 shl 10
  VERTEX_ATTRIBUTE_QTEXCOORD1* = 1 shl 11
  VERTEX_ATTRIBUTE_JOINTS* = 1 shl 12
  VERTEX_ATTRIBUTE_WEIGHTS* = 1 shl 13
  VERTEX_ATTRIBUTE_COUNT* = 1 shl 14